### ISSUE TITLE
Set angular distribution source via macro

### ISSUE THREAD

**Issue by op3** [uga-uga/utr#3]
Currently, the source volume for the angular distribution simulation is hard coded in `src/AngularDistributionGenerator.cc` and has to be manually changed for different geometries.

It is necessary to provide macros for both the dimensions of the sample box (`source_{x,y,z}`, `range_{x,y,z}`) and the source pv name. It should be possible to define multiple source pv names, such that experiments with multiple targets can be simulated.

**Comment by u-eff-gee** [comment]
Done
